// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Xnf46COP0Rcnrk48uMusAmksS7I3T1A',
    appId: '1:809556289247:web:dc50fd961b15f68b246b6a',
    messagingSenderId: '809556289247',
    projectId: 'quiz-app-fdb66',
    authDomain: 'quiz-app-fdb66.firebaseapp.com',
    storageBucket: 'quiz-app-fdb66.appspot.com',
    measurementId: 'G-K9B0Z8Y1GE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDme5L0wqX18Lcz2O6GTlKUEBZO9lCSNNQ',
    appId: '1:809556289247:android:ac8e63ada4e1837c246b6a',
    messagingSenderId: '809556289247',
    projectId: 'quiz-app-fdb66',
    storageBucket: 'quiz-app-fdb66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi0a2oOePHArti3lCmW1V_JAdA2hntQ2k',
    appId: '1:809556289247:ios:efe59e9ecd9246cd246b6a',
    messagingSenderId: '809556289247',
    projectId: 'quiz-app-fdb66',
    storageBucket: 'quiz-app-fdb66.appspot.com',
    iosClientId: '809556289247-29e66slqgtss1fd1elk1akiqgbq06iqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi0a2oOePHArti3lCmW1V_JAdA2hntQ2k',
    appId: '1:809556289247:ios:efe59e9ecd9246cd246b6a',
    messagingSenderId: '809556289247',
    projectId: 'quiz-app-fdb66',
    storageBucket: 'quiz-app-fdb66.appspot.com',
    iosClientId: '809556289247-29e66slqgtss1fd1elk1akiqgbq06iqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
